application: gris
version: 1
runtime: python
api_version: 1

handlers:
- url: /proxy.py
  script: main.py
- url: /reader/
  static_files: reader/index.html
  upload: reader/index.html
- url: /reader/(.+)
  static_files: reader/\1
  upload: reader/.*
